version: '3'

volumes:
  db_value:
  static_value:
  media_value:

services:

  db:
    image: postgres:13.10
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: wuldpwnz/taski_backend
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    env_file:
      - .env

  frontend:
    image: wuldpwnz/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend