# Generated by Django 2.2.19 on 2023-06-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_added_related_name_to_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина для покупок', 'verbose_name_plural': 'Корзина для покупок'},
        ),
    ]
