# Generated by Django 2.2.19 on 2023-06-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_user_model_username_field_for_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
